---
title: "Statistical Models and Data Mining Class Project"
author: "Group Project"
date: "Aug 2024"
---

## Regression Project: Amazon Order Cost Prediction

-   Developed a predictive cost estimation model in R for Amazon orders, conducting exploratory data analysis and visualizing key trends to inform feature selection and model design.
-   Preprocessed and cleaned data to ensure model accuracy; implemented multiple machine learning algorithms, including linear and lasso regression, random forest, SVM, XGBoost, and neural networks.
-   Optimized model performance through hyperparameter tuning and applied model stacking techniques; evaluated models using RMSE and presented comparative results through visualizations.
Download [Report](/Amazon Order Report.pdf)

## Classification Project: 2020 United States Presidential Election Winner Prediction

-   Designed and developed a predictive model to forecast the winner of the 2020 US Presidential Election, utilizing exploratory data analysis to uncover and visualize key trends for improved insights.
-   Preprocessed datasets and implemented a range of machine learning algorithms, including logistic regression, random forest, SVM, and KNN, to create a robust predictive framework.
-   Tuned hyperparameters and applied model stacking techniques to enhance predictive accuracy and visualized comparative results to effectively assess model performance.
Download [Report](/Election Classification Report.pdf)
