---
title: "Experiences"
---

## Research Experience

### University of California, Los Angeles  
**Undergraduate Researcher with Professor Xiaowu Dai**  
Los Angeles, CA | Jun 2024 – Oct 2024

- Conducted research inspired by Doyle Group’s study “Identifying General Reaction Conditions by Bandit Optimization,” focusing on optimizing chemical reactions conditions using machine learning techniques.
- Tested a broader range of parameters and algorithm variations (e.g., epsilon-greedy, UCB, Thompson Sampling, Bayesian UCB) under simulated scenarios, then applied findings to identify optimal reaction conditions.
- Enhanced the accuracy in identifying optimal ligands for C-H arylation to 88% with a new tested variation. Visualized results to compare algorithm performance.
- Performed in-depth regret analysis on algorithm outcomes using Python and R, and visualized results.

Download [Report](/Pinyi_Li_s_Project__Bandit_in_Chemistry.pdf) <br>
[View Project on GitHub](https://github.com/YellowLeaf926/Bandit-Algorithm-in-Chemistry)


### University of California, Santa Barbara  
**Research Assistant in Professor Arnab Mukherjee’s Lab**  
Santa Barbara, CA | Sept 2022 – June 2023

- Prepared essential growth media and reagents including RPMI, agar gel, and DMEM for cellular experiments, ensuring precise formulation and quality control.
- Performed tissue culture operations such as cell maintenance, splitting, and cryopreservation; executed advanced molecular cloning techniques including primer design, PCR, gel electrophoresis, gel extraction, Gibson assembly, bacterial transformation, and plasmid preparation (mini/midi prep).

## Professional Experience
### Data Analyst Intern, Deloitte AI Institute  
Shanghai, China | Aug 2023 – Sept 2023

- Evaluated AI model performance across general knowledge, logical reasoning, and translation tasks, documenting accuracy metrics, identifying improvement areas, and compiling pricing data to support commercial deployment strategies.
- Tested and analyzed nearly 100 AI plugins for office applications, assessing functionality, requirement alignment, and user experience. Provided detailed feedback on key features, input-output formats, and potential issues for real-world usage.